import poster from "./poster.png";

export const movies = [
    {
        id: 'mulan',
        title: 'Mulan',
        category: ['Action', 'Adventure', 'Drama'],
        year: '2024',
        photo: poster,
        rates: '9,8',
        votes: '74',
    },
    {
        id: 'terminator',
        title: 'Terminator',
        category: null,
        year: '2023',
        photo: poster,
        rates: '7,1',
        votes: '39',
    },
    {
        id: 'mumia',
        title: 'Mumia',
        category: ['Action'],
        year: null,
        photo: poster,
        rates: '6,2',
        votes: '53',
    },
    {
        id: 'oppenheimer',
        title: 'Oppenheimer',
        category: ['Action', 'Adventure'],
        year: '2021',
        photo: poster,
        rates: '7,3',
        votes: '121',
    },
    {
        id: 'mulan1',
        title: 'Mulan long title long title Mulan long',
        category: ['Action', 'Adventure', 'Drama'],
        year: '2024',
        photo: poster,
        rates: '5,8',
        votes: '44',
    },
    {
        id: 'terminator1',
        title: 'Terminator',
        category: ['Drama'],
        year: '2023',
        photo: poster,
        rates: '8,8',
        votes: '25',
    },
    {
        id: 'mumia1',
        title: 'Mumia',
        category: ['Action'],
        year: '2022',
        photo: poster,
        rates: '7,8',
        votes: '36',
    },
    {
        id: 'oppenheimer1',
        title: 'Oppenheimer',
        category: ['Action', 'Adventure'],
        year: '2021',
        photo: poster,
        rates: '4,8',
        votes: '32',
    }
];